import { GetArrayInnerType } from "../../types/utils";
import { DataElementDisaggregated } from "./DataElementDisaggregated";
import { Id, NamedRef, Ref } from "./ReferenceObject";

const models = ["dataSet", "program"] as const;
export type Model = GetArrayInnerType<typeof models>;
export type Models = Record<Model, boolean>;

export type OrgUnitSelectionSetting = "generation" | "import" | "both";
export type DuplicateToleranceUnit = "day" | "week" | "month" | "year";
export type DuplicateExclusion = Record<Id, Id[]>;

type DataSetId = Id;
type ProgramStageId = Id;
export type DataSetDataElementsFilter = Record<DataSetId, DataElementDisaggregated[]>;
export type ProgramStageFilter = Record<
    ProgramStageId,
    { dataElementsExcluded: Ref[]; attributesIncluded: Ref[]; externalDataElementsIncluded: Ref[] }
>;
export type ProgramStagePopulateEventsForEveryTei = Record<ProgramStageId, boolean>;

export interface DataFormTemplate {
    relationships: Record<DataFormId, Array<{ templateId: TemplateId }>>;
}

export const autogeneratedTemplateId = "autogenerated";
type AutogeneratedTemplateId = typeof autogeneratedTemplateId;
type DataFormId = Id;
type TemplateId = Id | AutogeneratedTemplateId;

export interface AppSettings {
    models: Record<Model, boolean>;
    permissionsForGeneration: NamedRef[];
    permissionsForSettings: NamedRef[];
    permissionsForImport: NamedRef[];
    allPermissionsForGeneration: boolean;
    allPermissionsForSettings: boolean;
    allPermissionsForImport: boolean;
    orgUnitSelection: OrgUnitSelectionSetting;
    duplicateEnabled: boolean;
    duplicateExclusion: DuplicateExclusion;
    duplicateTolerance: number;
    duplicateToleranceUnit: DuplicateToleranceUnit;
    dataSetDataElementsFilter: DataSetDataElementsFilter;
    programStageFilter: ProgramStageFilter;
    programStagePopulateEventsForEveryTei: ProgramStagePopulateEventsForEveryTei;
    dataFormTemplate: DataFormTemplate;
}
