import { Id } from "./ReferenceObject";

export interface DataFormTemplate {
    relationships: Record<DataFormId, Array<{ templateId: TemplateId }>>;
}

export const autogeneratedTemplateId = "autogenerated";
type AutogeneratedTemplateId = typeof autogeneratedTemplateId;

type DataFormId = Id;
type TemplateId = Id | AutogeneratedTemplateId;
