import _ from "lodash";
import i18n from "../../locales";
import { autogeneratedTemplateId } from "../entities/AppSettings";
import { NamedRef } from "../entities/ReferenceObject";
import { TemplateRepository } from "../repositories/TemplateRepository";

export class GetCustomTemplatesUseCase {
    constructor(private templateRepository: TemplateRepository) {}

    async execute(): Promise<NamedRef[]> {
        const templates = await this.templateRepository.getTemplates();
        const autogeneratedTemplate: NamedRef = { name: i18n.t("Autogenerated"), id: autogeneratedTemplateId };

        return _(templates)
            .filter(template => template.type === "custom")
            .map(template => _.pick(template, ["id", "name"]))
            .concat([autogeneratedTemplate])
            .value();
    }
}
