import _ from "lodash";
import { UseCase } from "../../CompositionRoot";
import Settings from "../../webapp/logic/settings";
import { DataForm } from "../entities/DataForm";
import { CustomTemplate } from "../entities/Template";
import { InstanceRepository } from "../repositories/InstanceRepository";

interface ExecuteOptions {
    settings: Settings;
    customTemplates: CustomTemplate[];
}

export class GetDataFormsForGenerationUseCase implements UseCase {
    constructor(private instance: InstanceRepository) {}

    public async execute(options: ExecuteOptions): Promise<{ dataSets: DataForm[]; programs: DataForm[] }> {
        const dataSets = await this.instance.getDataForms({ type: ["dataSets"] });
        const programs = await this.instance.getDataForms({ type: ["programs"] });

        return {
            dataSets: this.splitCustomAndAutogenerated(dataSets, options),
            programs: this.splitCustomAndAutogenerated(programs, options),
        };
    }

    private splitCustomAndAutogenerated(dataForms: DataForm[], options: ExecuteOptions): DataForm[] {
        const { customTemplates, settings } = options;

        return _(dataForms)
            .flatMap(dataForm => {
                const enabledTemplateIds = settings.getTemplateIdsForDataForm(dataForm);

                const dataFormsAutogenerated = customTemplates
                    .filter(template => template.dataFormId.type === "value" && template.dataFormId.id === dataForm.id)
                    .map(
                        (template): DataForm => ({
                            ...dataForm,
                            id: template.id,
                            name: template.name,
                        })
                    );

                const dataFormsDefault = customTemplates
                    .filter(
                        template =>
                            template.isDefault &&
                            template.dataFormType.type === "value" &&
                            template.dataFormType.id === dataForm.type
                    )
                    .map(
                        (template): DataForm => ({
                            ...dataForm,
                            id: `${dataForm.id}-${template.id}`,
                            name: `${dataForm.name} (${template.name})`,
                        })
                    );

                return _(dataFormsAutogenerated)
                    .concat(dataFormsDefault)
                    .concat(settings.showAutogeneratedForms ? [dataForm] : [])
                    .filter(dataForm_ => settings.isDataFormVisibleForCurrentUser(dataForm_.id))
                    .filter(
                        dataForm_ =>
                            !enabledTemplateIds ||
                            enabledTemplateIds.includes(
                                dataForm_.id.includes("-") ? dataForm_.id.split("-")[1] || "" : dataForm_.id
                            )
                    )
                    .value();
            })
            .sortBy(template => template.name.toLowerCase())
            .value();
    }
}
